[build]
  publish = "public"
  command = "npm run build"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"
